parent_cfg: configs/mvsgs/dtu_pretrain.yaml

train_dataset_module: lib.datasets.colmap.mvsgs
test_dataset_module: lib.datasets.colmap.mvsgs

mvsgs:
    eval_center: True
    reweighting: True
    scale_factor: 12
    cas_config:
        render_if: [False,True]
        volume_planes: [16,8]
    train_input_views: [1,2,3]

# train_dataset:
#     data_root: 'dtu_data/dtu_colmap'
#     split: 'train'
#     scene: scan24
#     input_h_w: [480, 640]
#     input_ratio: 1.
#     # scene: ''

# test_dataset:
#     data_root: 'dtu_data/dtu_colmap'
#     split: 'test'
#     scene: scan24
#     input_h_w: [480, 640]
#     input_ratio: 1.
#     # scene: ''

train_dataset:
    data_root: '/home/zhaoyibin/3DRE/3DGS/FatesGS/DTU/set_23_24_33'
    split: 'train'
    scene: scan24
    input_h_w: [480, 640]
    input_ratio: 2.
    # scene: ''

test_dataset:
    data_root: '/home/zhaoyibin/3DRE/3DGS/FatesGS/DTU/set_23_24_33'
    split: 'test'
    scene: scan24
    input_h_w: [480, 640]
    input_ratio: 2.
    # scene: ''

